/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.opredis;

import java.io.*;
import java.net.*;

public class App {

    public static void main(String[] args) {
        Rserver.startServer();
    }
}
